/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "tertiary": "#586062",
        "primary-container": "#ff6b00",
        "primary": "#a04100",
        "on-secondary-container": "#656464",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "on-primary-fixed": "#351000",
        "tertiary-fixed-dim": "#c1c8ca",
        "inverse-primary": "#ffb693",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb693",
        "on-primary-container": "#572000",
        "on-tertiary-container": "#2b3234",
        "surface-container-highest": "#e1e3e4",
        "secondary": "#5f5e5e",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#e5e2e1",
        "primary-fixed": "#ffdbcc",
        "on-secondary": "#ffffff",
        "outline": "#8e7164",
        "on-tertiary-fixed": "#161d1f",
        "tertiary-fixed": "#dde4e6",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "surface-container": "#edeeef",
        "on-tertiary-fixed-variant": "#41484a",
        "surface": "#f8f9fa",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#a04100",
        "surface-dim": "#d9dadb",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#e2bfb0",
        "on-surface-variant": "#5a4136",
        "on-primary-fixed-variant": "#7a3000",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-container": "#939a9c",
        "inverse-surface": "#2e3132"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "xl": "80px",
        "base": "8px",
        "lg": "48px",
        "gutter": "24px",
        "sm": "12px",
        "margin-mobile": "16px",
        "md": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
